language: java
before_install:
- openssl aes-256-cbc -K $encrypted_1217fe259264_key -iv $encrypted_1217fe259264_iv
  -in deploy_rsa.enc -out deploy_rsa -d
after_success:
- ./gradlew dist
- rsync -ve "ssh -o StrictHostKeyChecking=no -i deploy_rsa" desktop/build/libs/desktop-1.0.jar alynn@alynn.co.uk:public_html/space.jar
